名称:卡刷包转线刷包

于：
  观看：
    类型：[开始]
    
环境：
  ROM_URL ： https : //bigota.d.miui.com/V14.0.23.8.22.DEV/miui_NUWA_V14.0.23.8.22.DEV_7af7c43a24_14.0.zip
  ROM_版本： miui23.8.22
  TZ :亚洲/上海

职位：
  制作：
    运行： ubuntu-latest

    步骤：

    -名称：安装Python 3.7
      使用： actions/setup-python@v1
      与：
          python-版本：3.7
    - name :初始化环境
      运行：|
        光盘~
        sudo -E apt-get -qq 更新
        sudo -E apt-get -qq 安装 p7zip gzip
        pip 安装 bsdiff4
        python -m pip 安装 protobuf

    -名称：清理磁盘空间
      运行：|
        docker rmi `docker images -q`
        sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
        sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* 火狐谷歌* dotnet* powershell openjdk* mysql* php*
        sudo -E apt-get -y 自动删除 --purge
        sudo -E apt-get clean
        
    - name :克隆工具源代码
      运行：|
       光盘~
       git 克隆 https://github.com/vm03/payload_dumper.git
       git 克隆 https://github.com/yyzq2/RedmiK40FastbootFlashTool.git
  
    -名称：下载ROM
      运行：|
       光盘~
       wget -O rom.zip $ROM_URL
   
    -名称：解压ROM
      运行：|
       光盘~
       解压 rom.zip -d Payload_dumper
    
    -名称：解包payload.bin
      运行：|
       光盘~
       cd 负载转储器
       python Payload_dumper.py Payload.bin
   
    - name :资源为线路刷包
      运行：|
       光盘~
       mv ~/payload_dumper/output/* ~/RedmiK40FastbootFlashTool/images
       7za a -v2g -r $ROM_Version.7z ~/RedmiK40FastbootFlashTool/*
    
    - name: Upload to WeTransfer
      run: |
        cd ~
        curl -sL https://git.io/file-transfer | sh
        ./transfer wet $ROM_Version.7z.001
        ./transfer wet $ROM_Version.7z.002

